### ISSUE TITLE
No such file or directory: 'ffmpeg'

### ISSUE THREAD

**Issue by meeker0** [AbirHasan2005/VideoCompress#25]
After download is finished "No such file or directory: 'ffmpeg'" shows on log.
full log [here](https://katb.in/omodojazoru)

**Comment by meeker0** [comment]
Closing this issue ! Because of user side deploy problem !

**Comment by AbirHasan2005** [comment]
Install `ffmpeg`

**Comment by meeker0** [comment]
It's already in the dockerfile ! I was using heroku cli for deploy not running it from local and I haven't modified your dockerfile . However, using button for deploy works fine !

**Comment by AbirHasan2005** [comment]
You have to change heroku stack to container.

CMD:
`heroku stack:set container -a app_name`
